./serialconv /share/apps/files/convolution/images/im01.ppm /share/apps/files/convolution/kernel/kernel3x3_Edge.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im02.ppm /share/apps/files/convolution/kernel/kernel3x3_Edge.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im03.ppm /share/apps/files/convolution/kernel/kernel3x3_Edge.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im04.ppm /share/apps/files/convolution/kernel/kernel3x3_Edge.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im05.ppm /share/apps/files/convolution/kernel/kernel3x3_Edge.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im06.ppm /share/apps/files/convolution/kernel/kernel3x3_Edge.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im07.ppm /share/apps/files/convolution/kernel/kernel3x3_Edge.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im10.ppm /share/apps/files/convolution/kernel/kernel3x3_Edge.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im01.ppm /share/apps/files/convolution/kernel/kernel5x5_Sharpen.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im02.ppm /share/apps/files/convolution/kernel/kernel5x5_Sharpen.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im03.ppm /share/apps/files/convolution/kernel/kernel5x5_Sharpen.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im04.ppm /share/apps/files/convolution/kernel/kernel5x5_Sharpen.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im05.ppm /share/apps/files/convolution/kernel/kernel5x5_Sharpen.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im06.ppm /share/apps/files/convolution/kernel/kernel5x5_Sharpen.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im07.ppm /share/apps/files/convolution/kernel/kernel5x5_Sharpen.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im10.ppm /share/apps/files/convolution/kernel/kernel5x5_Sharpen.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im01.ppm /share/apps/files/convolution/kernel/kernel25x25_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im02.ppm /share/apps/files/convolution/kernel/kernel25x25_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im03.ppm /share/apps/files/convolution/kernel/kernel25x25_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im04.ppm /share/apps/files/convolution/kernel/kernel25x25_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im05.ppm /share/apps/files/convolution/kernel/kernel25x25_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im06.ppm /share/apps/files/convolution/kernel/kernel25x25_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im07.ppm /share/apps/files/convolution/kernel/kernel25x25_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im10.ppm /share/apps/files/convolution/kernel/kernel25x25_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im01.ppm /share/apps/files/convolution/kernel/kernel49x49_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im02.ppm /share/apps/files/convolution/kernel/kernel49x49_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im03.ppm /share/apps/files/convolution/kernel/kernel49x49_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im04.ppm /share/apps/files/convolution/kernel/kernel49x49_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im05.ppm /share/apps/files/convolution/kernel/kernel49x49_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im06.ppm /share/apps/files/convolution/kernel/kernel49x49_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im07.ppm /share/apps/files/convolution/kernel/kernel49x49_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im10.ppm /share/apps/files/convolution/kernel/kernel49x49_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im01.ppm /share/apps/files/convolution/kernel/kernel99x99_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im02.ppm /share/apps/files/convolution/kernel/kernel99x99_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im03.ppm /share/apps/files/convolution/kernel/kernel99x99_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im04.ppm /share/apps/files/convolution/kernel/kernel99x99_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im05.ppm /share/apps/files/convolution/kernel/kernel99x99_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im06.ppm /share/apps/files/convolution/kernel/kernel99x99_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im07.ppm /share/apps/files/convolution/kernel/kernel99x99_random.txt ./prova.ppm 1
./serialconv /share/apps/files/convolution/images/im10.ppm /share/apps/files/convolution/kernel/kernel99x99_random.txt ./prova.ppm 1
